name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v5

      - name: ☕️ Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit
          add-job-summary: on-failure
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: 🛠 Build
        run: ./gradlew build --scan

      - name: 💹 Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: 'Test Results'
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: 'java-junit'
          list-suites: 'failed'
          list-tests: 'failed'

      - name: 📋 Upload build reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: build-reports
          path: build/reports/